- name: Install Oh My ZSH
  hosts: local
  become: true
  # vars:
  #   # target_user: "{{ ansible_user_id }}"
  #   target_user: "{{ ansible_env.USER}}"
  #   # target_home: "{{ ansible_env.HOME }}"
  #   target_home: "{{ ansible_env.HOME }}"
  
  tasks:
    - name: Install required system packages necessary for ZSH
      ansible.builtin.package:
        name: 
          - zsh
          - git
          - curl
          - util-linux-user
        state: present
      become: true
    
    - name: Change default shell
      ansible.builtin.user:
        name: "{{ target_user }}"
        shell: /bin/zsh
      become: true
    
    - name: Check if Oh My Zsh is already installed
      ansible.builtin.stat:
        path: "{{ target_home }}/.oh-my-zsh"
      register: oh_my_zsh_stat
      become: false

    - name: Download the Oh My Zsh installer
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/install_ohmyzsh.sh
        mode: '0755'
      when: not oh_my_zsh_stat.stat.exists
      become: false

    - name: Execute Oh My Zsh installation script
      ansible.builtin.command:
        cmd: sh /tmp/install_ohmyzsh.sh --not-changedrc --unattended
      when: not oh_my_zsh_stat.stat.exists
      become: false

    - name: Remove installer script
      ansible.builtin.file:
        path: "/home/{{ target_user }}/install_ohmyzsh.sh"
        state: absent
      become: false
      become_user: "{{ target_user }}"

    - name: Change user's default shell to zsh
      ansible.builtin.user:
        name: "{{ target_user }}"
        shell: /bin/zsh
      become: yes