- name: Install Powerlevel10k
  hosts: local
  become: true
  vars:
    target_user: "{{ ansible_user_id }}"
    target_home: "{{ ansible_env.HOME }}"

  tasks:
    - name: Set user shell to zsh
      ansible.builtin.user:
        name: "{{ target_user }}"
        shell: /bin/zsh

    - name: Fix ownership of Oh My ZSH themes directory
      ansible.builtin.file:
        path: "{{ target_home }}/.oh-my-zsh/custom/themes"
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        recurse: true
        state: directory
        mode: '0755'

    - name: Install PowerLevel10K
      ansible.builtin.git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: "{{ target_home }}/.oh-my-zsh/custom/themes/powerlevel10k"
        depth: 1
        force: true
      become_user: "{{ target_user }}"

    - name: Download NerdFonts
      ansible.builtin.get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/Meslo.zip
        dest: "{{ target_home }}/Meslo.zip"
      become_user: "{{ target_user }}"

    - name: Fix ownership of Meslo directory if it exists
      ansible.builtin.file:
        path: "{{ target_home }}/Meslo"
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        recurse: true
        state: directory
        mode: '0755'

    - name: Extract font files
      ansible.builtin.unarchive:
        src: "{{ target_home }}/Meslo.zip"
        dest: "{{ target_home }}/Meslo"
      become_user: "{{ target_user }}"

    - name: Move font files to system fonts directory
      ansible.builtin.copy:
        src: "{{ target_home }}/Meslo"
        dest: /usr/share/fonts/Meslo
        owner: root

    - name: Update .zshrc with Powerlevel10k theme
      ansible.builtin.lineinfile:
        path: "{{ target_home }}/.zshrc"
        insertafter: EOF
        line: "source {{ target_home }}/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme"
      become: false