- name: Setup Python
  hosts: local
  vars:
    python_dev_package: "{{ 'python3-devel' if ansible_os_family == 'RedHat' else 'python3-dev' }}"

  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Install basic packages
      ansible.builtin.package:
        name:
          - "{{ python_dev_package }}"
          - python3-pip
          - vim
      become: true

    - name: Install UV
      ansible.builtin.shell:
        cmd: curl -LsSf https://astral.sh/uv/install.sh | sh
        creates: ~/.local/bin/uv
      register: install_uv_output
      become: false

    - name: UV install output
      ansible.builtin.debug:
        var: install_uv_output